
package com.customer.service.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2018-05-01T16:05:55.569+08:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "createCustomerFault", targetNamespace = "http://service.customer.com/types/v1")
public class CreateCustomerFault extends Exception {
    
    private com.customer.service.types.v1.CreateCustomerFault createCustomerFault;

    public CreateCustomerFault() {
        super();
    }
    
    public CreateCustomerFault(String message) {
        super(message);
    }
    
    public CreateCustomerFault(String message, Throwable cause) {
        super(message, cause);
    }

    public CreateCustomerFault(String message, com.customer.service.types.v1.CreateCustomerFault createCustomerFault) {
        super(message);
        this.createCustomerFault = createCustomerFault;
    }

    public CreateCustomerFault(String message, com.customer.service.types.v1.CreateCustomerFault createCustomerFault, Throwable cause) {
        super(message, cause);
        this.createCustomerFault = createCustomerFault;
    }

    public com.customer.service.types.v1.CreateCustomerFault getFaultInfo() {
        return this.createCustomerFault;
    }
}
