package com.customer.service.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2018-05-01T16:05:55.637+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "CustomerService", 
                  wsdlLocation = "file:/D:/project/customer-service-impl/src/main/resources/wsdl/customer-service.wsdl",
                  targetNamespace = "http://service.customer.com/v1") 
public class CustomerService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.customer.com/v1", "CustomerService");
    public final static QName CustomerServicePort = new QName("http://service.customer.com/v1", "CustomerServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/project/customer-service-impl/src/main/resources/wsdl/customer-service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/project/customer-service-impl/src/main/resources/wsdl/customer-service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CustomerService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CustomerServicePort
     */
    @WebEndpoint(name = "CustomerServicePort")
    public CustomerServicePort getCustomerServicePort() {
        return super.getPort(CustomerServicePort, CustomerServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerServicePort
     */
    @WebEndpoint(name = "CustomerServicePort")
    public CustomerServicePort getCustomerServicePort(WebServiceFeature... features) {
        return super.getPort(CustomerServicePort, CustomerServicePort.class, features);
    }

}
