
package com.customer.service.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2018-05-01T16:05:55.549+08:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "deleteCustomerFault", targetNamespace = "http://service.customer.com/types/v1")
public class DeleteCustomerFault extends Exception {
    
    private com.customer.service.types.v1.DeleteCustomerFault deleteCustomerFault;

    public DeleteCustomerFault() {
        super();
    }
    
    public DeleteCustomerFault(String message) {
        super(message);
    }
    
    public DeleteCustomerFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DeleteCustomerFault(String message, com.customer.service.types.v1.DeleteCustomerFault deleteCustomerFault) {
        super(message);
        this.deleteCustomerFault = deleteCustomerFault;
    }

    public DeleteCustomerFault(String message, com.customer.service.types.v1.DeleteCustomerFault deleteCustomerFault, Throwable cause) {
        super(message, cause);
        this.deleteCustomerFault = deleteCustomerFault;
    }

    public com.customer.service.types.v1.DeleteCustomerFault getFaultInfo() {
        return this.deleteCustomerFault;
    }
}
