
package com.customer.service.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2018-05-01T16:05:55.489+08:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "updateCustomerFault", targetNamespace = "http://service.customer.com/types/v1")
public class UpdateCustomerFault extends Exception {
    
    private com.customer.service.types.v1.UpdateCustomerFault updateCustomerFault;

    public UpdateCustomerFault() {
        super();
    }
    
    public UpdateCustomerFault(String message) {
        super(message);
    }
    
    public UpdateCustomerFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UpdateCustomerFault(String message, com.customer.service.types.v1.UpdateCustomerFault updateCustomerFault) {
        super(message);
        this.updateCustomerFault = updateCustomerFault;
    }

    public UpdateCustomerFault(String message, com.customer.service.types.v1.UpdateCustomerFault updateCustomerFault, Throwable cause) {
        super(message, cause);
        this.updateCustomerFault = updateCustomerFault;
    }

    public com.customer.service.types.v1.UpdateCustomerFault getFaultInfo() {
        return this.updateCustomerFault;
    }
}
